### ISSUE TITLE
fdrs_globals.h missing

### ISSUE THREAD

**Issue by jonburch** [timmbogner/Farm-Data-Relay-System#109]
On compiling I get fdrs_globals.h is missing. I've downloaded it a couple times and it is not in the src folder per the instructions. Any advice? thanks

**Comment by timmbogner** [comment]
I'm actually re-opening this, in case anyone else faced this problem recently.
I'm very sorry about the confusion!

**Comment by jonburch** [comment]
I appreciate your attention to this.
