### ISSUE TITLE
LoRa Gateway neighbor sending/receiving issue

### ISSUE THREAD

**Issue by timmbogner** [timmbogner/Farm-Data-Relay-System#155]
Hello everyone,
The asynchronous LoRa functionality has been a real test of my coding abilities. There is currently a problem with LoRa gateways not being able to send data after they have received a packet.
I'm working on it, and will post more details if I can't get to the bottom of it.

Thanks for your patience!

**Comment by timmbogner** [comment]
Okay I think it's sorted out and better than ever.

@aviateur17 This wasn't the problem, but FYI I also it so the gateway never requests an ACK for a DataReading (it was disabled for broadcast, now for neighbors also). Unless we get an ACK system set up for the async release function, I don't think it should be an issue.

**Comment by f2knpw** [comment]
Hi Timm,
[Latest release](https://github.com/timmbogner/Farm-Data-Relay-System/blob/main/src/fdrs_gateway_lora.h) of does fix this issue !
Thanks again

**Comment by aviateur17** [comment]
> @aviateur17 This wasn't the problem, but FYI I also made it so the gateway never requests an ACK for a DataReading (it was disabled for broadcast, now for neighbors also). Unless we get an ACK system set up for the async release function, I don't think it should be an issue.

Sounds good, I'll take a look and see what I can figure out after I get the timekeeping stuff close to being done.

**Comment by timmbogner** [comment]
@aviateur17 Something I've been working on today is checking out how the async LoRa release reacts to a buffer that contains >250 bytes. After a small change I have it working as intended. I'm entering approx. 3 boatloads of DataReadings into the terminal and the gateway is splitting and sending four full (251 byte) packets and a 34 byte packet. Very satisfying. However, the receiving gateway can't keep up when receiving back-to-back packets AND displaying debugs at the same time. It drops one or two unless FDRS_DEBUG is disabled. I'll probably go through and remove or abridge some messages there soon.

I'm not even using OLED... I imagine that wouldn't help either.
