### ISSUE TITLE
Potential usage for buttons/switches/rotary encoders

### ISSUE THREAD

**Issue by luigi311** [timmbogner/Farm-Data-Relay-System#18]
Is it possible to use this to send data such as button presses/flipping a switch/rotary encoder? I see its mostly used for sensor data every x amount of time but i would like to also use this to have an esp-32 with a rotary encoder in deep sleep until the encoder is rotated or the button is pressed and send that over to the gateway.

**Comment by Devilbinder** [comment]
Yes this is possible. All you need to do is wrap the send block in a if on change block.
It will look something like this.
```
void loop() {
    your wake state
    data1 = readButton();
    
    if button change
      FDRS.load(data1,BUTTON_T);
      FDRS.send();
      
    your wait state
}
```

**Comment by lekrom** [comment]
Sounds good. I agree that some processing of the rotary encoders should be done on the sensor node side. It will quickly get very clumsy otherwise.
