### ISSUE TITLE
Support for username and password for mqtt broker

### ISSUE THREAD

**Issue by gco33** [timmbogner/Farm-Data-Relay-System#28]
Could it be possible to add support for username and password for mqtt broker ?

My mosquitto broker is "protected" by a username and password and I am very interested of using FDRS which is exactly what I had in mind when look on espnow technology for my home sensors.

The usage of username and password for mqtt must be optional for people who are not interested of that.

Thanks for sharing this great project.

**Comment by Devilbinder** [comment]
Was handled in this PR https://github.com/timmbogner/Farm-Data-Relay-System/pull/23

**Comment by thefeiter** [comment]
Yep, this is already available in the dev branch.

**Comment by gco33** [comment]
Cool, I will test it. Thanks
