### ISSUE TITLE
DEBUG define with PlatformIO will cause build to fail

### ISSUE THREAD

**Issue by aviateur17** [timmbogner/Farm-Data-Relay-System#47]
Probably not to concerned about PlatformIO support but if compiling the project with PlatformIO and using the #define DEBUG in fdrs_functions.h and fdrs_config.h the build will fail:

In file included from /home/xxxx/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/newlib/stdio.h:47:0,
                 from /home/xxxx/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/esp32/esp_err.h:17,
                 from /home/xxxx/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/esp32/esp_now.h:19,
                 from src/main.cpp:9:
/home/xxxxx/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/newlib/sys/reent.h:463:10: error: #if with no expression

Changing DEBUG to something else in both of those files seems to resolve the issue.

**Comment by thefeiter** [comment]
:warning: This has to be mentioned in a changelog. It caused some confusion for me, since no debug messages were sent because I copied the fdrs_config file.

**Comment by aviateur17** [comment]
Resolved in dev branch to be merged with main.
