### ISSUE TITLE
ESP32 WROOM-DA WITH TWO ANTENNAS

### ISSUE THREAD

**Issue by Telepresent** [timmbogner/Farm-Data-Relay-System#5]
Hi, I would like to know if it would be possible to use a single ESP32 WROOM-DA with two antennas as a repeater.
https://hackaday.com/2022/04/04/esp32-is-two-better-than-one/

Regards

**Comment by timmbogner** [comment]
Do you mean to essentially listen with one antenna and repeat the signal with the second?
It sounds possible!
I was also inspired by Andreas's video and will be investigating the possibilities with this module. I'm thinking of a way for sensors to ping gateways and choose the best antenna based on RSSI. 

I'll keep this open until I have done some more research!

**Comment by Telepresent** [comment]
Yes, I also think its possible!

Regards
