### ISSUE TITLE
enhancement: Add LoRa Tx Power setting

### ISSUE THREAD

**Issue by aviateur17** [timmbogner/Farm-Data-Relay-System#66]
Would be nice to be able to set LoRa TX power.   17dB is default.  Range is between 0 and 20 dB.   Less power means less battery used.

LoRa.setTxPower();

Low priority.

**Comment by timmbogner** [comment]
Agreed, btw. Forgot to respond when I saw this. 

Tx power and any other LoRa options I may have overlooked. That'll be a quick one I'll do one of these days.

**Comment by timmbogner** [comment]
I said I was going to do this, but have busied myself with other things now. If you want to take care of these changes you're welcomed to. 👍

**Comment by aviateur17** [comment]
Will do.  Should be an easy one.   I'm working on the sensor READING_ID issue first and then will work on this one.   

Wondering if the SystemPacket communication from the gateway to the sensors is the next big feature to work on.  I see you have started that with the ping.

**Comment by aviateur17** [comment]
Submitted PR so closing this discussion.
